### ISSUE TITLE
The pre-training budget on WebVid-2M

### ISSUE THREAD

**Issue by mzhaoshuai** [m-bain/frozen-in-time#29]
Thanks for your work.
I am interested in the pre-training budget on WebVid-2M.
Could you tell us how many GPUs and how much time you cost for pre-training on WebVid-2M?

**Comment by m-bain** [comment]
Hi,
I used 4x48GB gpus for around 2 weeks if I recall correctly. As described in the readme, you want to spend about 90% of the training budget training on 1-frame. This is because most of the knowledge can be learned in the 1-frame setting and you can fit much bigger batches + higher throughput with 1-frame. You can the spend the remaining 10% on 4-frames.
Best,
Max
