### ISSUE TITLE
why noy evaluate your model on HowTo100 dataset

### ISSUE THREAD

**Issue by ForawardStar** [m-bain/frozen-in-time#35]
Hello, Wonderful project! Here is a small question: why noy evaluate your model on HowTo100 dataset? As we all konwn, HowTo100 also contains video-text pairs which can be used for video-text retrieval. I suppose it is a suitable dataset that can be fintuned on. Thanks.

**Comment by m-bain** [comment]
Hi thank you! Good question.

In the paper we do show some initial results when pretraining (not evaluating) on howto100, and that subset size comparable to cc3m/webvid you get worse performance due to the noisy annotation.

If you mean why not downstream evaluation on howto100m, we typically don't see howto used for retrieval evaluation because its automatic annotation (noisy). Did you see papers that do this? I would be intrigued to see how the assign ground truth.

**Comment by ForawardStar** [comment]
Thanks for your reply! As for your question, I found a paper titled _HERO: Hierarchical Encoder for Video+Language Omni-representation Pre-training, which construct two new datasets from Howto100 ? I wonder if this has inspired you?  Welcome to communicate with me at any time.
